jb4dc:
  system-caption: 门户网站
  system-title: JBuild4DC-门户网站
  warning-operation-code: jb4d82
  is-debug: true
  host:
    operation-system: Window
  sso:
    server:
      name: JB4DC-SSO-WEB-SERVER
      address: http://localhost:9101
      context-path: /SSOSystem
      view:
        login: /Controller/LoginSSOView
        logout: /logout
      excluded: /**
  builder:
    server:
      name: JB4DC-BUILDER-WEB-SERVER
      #address: http://localhost:9103
      context-path: /JB4DCBuilder

spring:
  application:
    name: JB4DC-SITE-TL-WEB-SERVER
    inetutils:
      #客户端的IP
      preferred-networks: 192.168.3.153
  liquibase:
    enabled: false
  thymeleaf:
    prefix: file:///D:/JavaProject/jb4dc/jb4dc-site-root/Site_TL/
    suffix: .html
    enabled: true
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:///D:/JavaProject/jb4dc/jb4dc-site-root/Site_TL/

server:
  port: 9105
  servlet:
    session:
      timeout: 7200
    context-path: /SiteTL

eureka:
  client:
    serviceUrl:
      #服务端的地址
      #defaultZone: http://192.168.3.166:9092/eureka/
      defaultZone: http://localhost:9092/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.inetutils.preferred-networks}:${server.port}

logging:
  level:
    com:
      jb4dc:
        base:
          dbaccess: TRACE
        devmock:
          dao: TRACE
        sso:
          client: debug
        builder:
          client: debug

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 12000
        retryer: feign.Retryer.Default

